/**
 * App Redux Action Types
 */
// Sidebar
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const COLLAPSED_SIDEBAR = 'COLLAPSED_SIDEBAR';

// Auth Actions
export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';
export const UNCHECK_USER_SESSION = 'UNCHECK_USER_SESSION';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';
export const SWITCH_VIEW = 'SWITCH_VIEW';
